"""The manuscript: documents, the text projection, and (from Phase 2) anchors and snapshots."""

from .documents import (
    DEFAULT_KIND,
    MAX_CONTENT_BYTES,
    MAX_TITLE_LENGTH,
    ContentTooLargeError,
    Document,
    DocumentError,
    DocumentMeta,
    DocumentNotFoundError,
    DocumentStore,
    OutlineChapter,
    SaveResult,
    StaleVersionError,
    clean_title,
    serialize_content,
)
from .locator import DocumentLocator
from .projection import (
    BLOCK_SEPARATOR,
    MAX_DEPTH,
    SCENE_BREAK,
    Heading,
    InvalidDocumentError,
    Projection,
    count_words,
    empty_document,
    project,
    validate_document,
)

__all__ = [
    "BLOCK_SEPARATOR",
    "DEFAULT_KIND",
    "MAX_CONTENT_BYTES",
    "MAX_DEPTH",
    "MAX_TITLE_LENGTH",
    "SCENE_BREAK",
    "ContentTooLargeError",
    "Document",
    "DocumentError",
    "DocumentLocator",
    "DocumentMeta",
    "DocumentNotFoundError",
    "DocumentStore",
    "Heading",
    "InvalidDocumentError",
    "OutlineChapter",
    "Projection",
    "SaveResult",
    "StaleVersionError",
    "clean_title",
    "count_words",
    "empty_document",
    "project",
    "serialize_content",
    "validate_document",
]
