"""The manuscript: documents, the text projection, and (from Phase 2) anchors and snapshots."""

from .anchors import (
    ALL_STATUSES,
    EFFECTIVE_STATUS_SQL,
    STORED_STATUSES,
    AnchorStatus,
    effective_status,
)
from .documents import (
    DEFAULT_KIND,
    LIVE_ONLY,
    MAX_CONTENT_BYTES,
    MAX_TITLE_LENGTH,
    ContentTooLargeError,
    Document,
    DocumentError,
    DocumentMeta,
    DocumentNotFoundError,
    DocumentStore,
    OutlineChapter,
    ReorderMismatchError,
    SaveResult,
    StaleVersionError,
    clean_title,
    serialize_content,
)
from .locator import DocumentLocator
from .projection import (
    BLOCK_SEPARATOR,
    MAX_DEPTH,
    SCENE_BREAK,
    Heading,
    InvalidDocumentError,
    Projection,
    count_words,
    empty_document,
    project,
    validate_document,
)
from .snapshots import (
    HANDOVER_RETENTION,
    MAX_LABEL_LENGTH,
    Snapshot,
    SnapshotError,
    SnapshotMeta,
    SnapshotNotFoundError,
    SnapshotReason,
    SnapshotStore,
    capture_within,
    hash_content,
)

__all__ = [
    "ALL_STATUSES",
    "BLOCK_SEPARATOR",
    "DEFAULT_KIND",
    "EFFECTIVE_STATUS_SQL",
    "HANDOVER_RETENTION",
    "LIVE_ONLY",
    "MAX_CONTENT_BYTES",
    "MAX_DEPTH",
    "MAX_LABEL_LENGTH",
    "MAX_TITLE_LENGTH",
    "SCENE_BREAK",
    "STORED_STATUSES",
    "AnchorStatus",
    "ContentTooLargeError",
    "Document",
    "DocumentError",
    "DocumentLocator",
    "DocumentMeta",
    "DocumentNotFoundError",
    "DocumentStore",
    "Heading",
    "InvalidDocumentError",
    "OutlineChapter",
    "Projection",
    "ReorderMismatchError",
    "SaveResult",
    "Snapshot",
    "SnapshotError",
    "SnapshotMeta",
    "SnapshotNotFoundError",
    "SnapshotReason",
    "SnapshotStore",
    "StaleVersionError",
    "capture_within",
    "clean_title",
    "count_words",
    "effective_status",
    "empty_document",
    "hash_content",
    "project",
    "serialize_content",
    "validate_document",
]
